POST http://localhost:9999/api/tokens
Content-Type: application/json

{
  "username": "RendL",
  "password": "pass"
}

> {% client.global.set("auth_token", response.body.token); %}

###

GET http://localhost:9999/api/users
Authorization: Bearer {{auth_token}}

###

DELETE http://localhost:9999/api/users/4
Authorization: Bearer {{auth_token}}

###

POST http://localhost:9999/api/users/4
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "MOMO2",
  "password": "MOMO2",
  "admin": false
}

###

POST http://localhost:9999/api/tokens
Content-Type: application/json

{
  "username": "MOMO",
  "password": "MOMO"
}

> {% client.global.set("auth_token", response.body.token); %}

###

