POST https://auth-servisss.herokuapp.com/api/tokens
Content-Type: application/json

{
  "username": "RendL",
  "password": "pass"
}

> {% client.global.set("auth_token", response.body.token); %}

###

GET https://auth-servisss.herokuapp.com/api/users/me
Authorization: Bearer {{auth_token}}

###

DELETE http://localhost:9999/api/users/1
Authorization: Bearer {{auth_token}}

###

POST http://localhost:9999/api/users/new
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "username": "MOMO",
  "password": "MOMO"
}

###

POST https://auth-servisss.herokuapp.com/api/tokens
Content-Type: application/json

{
  "username": "MOMOO",
  "password": "MOMOO"
}

> {% client.global.set("auth_token", response.body.token); %}

###

